### ISSUE TITLE
All attendees and invited users deleted when event changed in Thunderbird Calendar

### ISSUE THREAD

**Issue by MarinaOCC** [kewisch/gdata-provider#156] opened 2021-01-28 18:30 UTC
### Describe the problem and steps to reproduce it:
Create event in Google Calendar and invite guests.
Open Calendar in Thunderbird.   Change event or save event.   All attendees deleted and event deleted from guests/attendees 
 google calendars.

**Comment by roccopietrini** [comment] 2021-01-29 08:32
Duplicate of this: https://github.com/kewisch/gdata-provider/issues/129

The only workaround is to set you calendar read-only in thunderbird and use the web interface to create events. I have been waiting for months for this fix.

**Comment by AntoniusGolly** [comment] 2021-09-01 10:27
This is aweful.

Thanks for the hint @roccopietrini

**Comment by kewisch** [comment] 2021-09-04 23:46
Apologies this has been an issue so long  💔 This is on my radar, fixing this with 91.0.2

**Closed by kewisch** 2021-09-04 23:46 UTC
Labels: duplicate

**Comment by rb1t** [comment] 2021-11-10 14:56
> 
> 
> @kewisch 91.2.0 here I create a google calendar event with attendees. I open it in thunderbird and I can see and edit everyone. But if I save it in thunderbird, all attendees are removed.

Same experience for me.

**Comment by Willeaton** [comment] 2022-07-19 11:52
This is still happening to me in version 102.0.0. When I come to the time of the event everyone in my meeting reports that they did have the event in their calendar but its now disappeared, this is because the event loses all invited guests and to my knowledge I am not modifying the event from thunderbird.

**Comment by AntoniusGolly** [comment] 2022-07-19 13:21
Same, for security reasons I have TB only in read-only mode. This is a huge drawback.

**Comment by ChrisiPK** [comment] 2022-11-22 15:03
Still seeing this behavior in 102.0.3. When I dismiss the notification for an event, it actually modifies the event and removes all invited attendees.

**Comment by ThierryBZH** [comment] 2023-12-22 15:02
Still existing in 115.0.2
Accepting/editing an event created on Google Agenda or dismissing reminder WILL REMOVE ATTENDEES!!! They'll receive a "Cancel" notification.

**Comment by simskij** [comment] 2024-01-25 17:00
Still seeing this as well as of yesterday with 115.0.2.

**Comment by fralund** [comment] 2024-01-29 09:06
Same here on 115.0.2

**Comment by RedwanFox** [comment] 2024-05-15 11:24
Have this problem too
