### ISSUE TITLE
Android Issue when delete only one event of a serie

### ISSUE THREAD

**Issue by Cybertaf** [kewisch/gdata-provider#38] opened 2019-12-04 12:21 UTC
Hi !
It's an issue I have since long time.
I have TB+Lightning on computer and Gmail calendar on 2 Android phone.
In Lightning, when I delete a single event from a series of recurring events, it synchronizes well with Gmail but on Android it removes all events in the series.
Any idea ?
Thanks.

**Comment by mogwa1** [comment] 2019-12-16 11:57
I seem to have the same problem.
I haven't pinned it down completely, but deleting one event of a recurring event, the entire series stops syncing to android.  I have the impression that also modifying a single event makes the recurring event disappear on android, but I haven't tested that thoroughly yet.  
As mentioned above, everything still looks fine in lightning and on calendar.google.com (i.e. google calendar webinterface).  It seems to be a problem with the native android google calendar sync because the problem occurs in all calendar apps that I tried.
I never had this problem during many years until I started using lightning a couple of months ago.

Could it be that the deletion of a single event from the recurring event is handled in a different way than the native google tools?  A way that the android native sync cannot handle?

**Comment by suskozaver** [comment] 2019-12-16 13:40
I can confirm the same issue, only mine goes further:
- i can't delete a recurring event in TB, no matter what, it doesn't get deleted
- if i delete one event in series of recurring events in Google Calendar or on my phone (Android), it doesn't get deleted in TB

After 3 show ups for meetings that were canceled, but stayed in my TB calendar, I had to switch back to web version of Google Calendar.

**Comment by Cybertaf** [comment] 2019-12-17 11:22
@mogwa1 
You described my issue exactly but you speak better english than me :)))
The only difference is that I had this problem a few years ago and I stopped using Lightning because of it.

**Comment by Cybertaf** [comment] 2020-10-08 10:26
Hi,
Is there a fix planned for this issue ?
BR

**Comment by mogwa1** [comment] 2020-10-08 11:02
@Cybertaf 
Since this issue first popped up, I switched over to using native caldav syncing in thunderbird.
So no addons required.  See this link for instructions on how to get the caldav URL for a specific google calendar: https://developers.google.com/calendar/caldav/v2/guide (see instructions near bottom of page).
This has been working fine for me so far.

**Comment by Cybertaf** [comment] 2020-10-08 11:42
@mogwa1 
Thanks for the tip, but my Gmail account is from G-Suite and the administrator did not activate Google Cloud Platform, so I can not create a project and/or activate API.
Thanks anyway.

**Comment by Cybertaf** [comment] 2020-10-08 12:08
@mogwa1 
Oh ! It looks like CalDAV is activated by default on my organisation !
Juste added CalDAV with this URL : https://apidata.googleusercontent.com/caldav/v2/adress@mails.com/events with OAuth and it's working !
I will test if working well !
Very big thanks to you !

**Comment by kewisch** [comment] 2021-09-19 20:32
When deleting an occurrence, I add an EXDATE to the recurrence section. I'm not sure why the Android App would not like this. If you like, you could try the following:


1) Open Error Console in Thunderbird, enable  "XHR" and "Requests" at the top right
2) Delete an occurrence on the android app
3) Synchronize in Thunderbird
4) Expand the request for `https://www.googleapis.com/calendar/v3/calendars/useremail/events?maxResults=1000&...`
5) In the response tab, expand until you reach the event whre you deleted the occurrence
6) Post the event json here. I'm particularly interested in the "recurrence" array.

I'm going to close this since you've found a different solution, but if you are up for testing please do reopen.

**Closed by kewisch** 2021-09-19 20:32 UTC
Labels: investigate
