### ISSUE TITLE
Calendars do not load at startup

### ISSUE THREAD

**Issue by chad-exc** [kewisch/gdata-provider#133] opened 2020-11-12 03:13 UTC
### Describe the problem and steps to reproduce it:

Upgraded to latest version of thunderbird, lightning, and provider.  Now  I have to unhide all google calendars each time I start Calendars in TB. For some reasons it is automatically hidden at each startup. (I go into lightning calendar tab and toggle eyeballs) I am not sure if it is to do with the add-on or the Calendar feature in TB, but please make sure that the calendar viewing preferences are stored at closing TB.

Also, when adding a new event, once the event is added, the "thinking" spinning mouse cursor starts going and doesn't stop spinning until I switch to a tab with lightning, and then back to main thunderbird mail layout. 

Running on Windows 10 Pro 1909
Thunderbird 78.4.3
Provider 78.0.1

**Comment by micter59** [comment] 2020-11-12 07:58
I confirm this bug. I have to do this on every startup of Thunderbird since a few versions now. It seems the behaviour of Thunderbird has change, as everything was ok just after the release of the plugin, at the end of august.

**Comment by joek666** [comment] 2020-11-13 17:34
Same issue for me as micter59.

Any ideas?

Thanks!

**Comment by jdigh** [comment] 2020-11-14 12:23
I have quite similar problems.
I have  to hide and dehide every google calendar in TB to get the calendar items on overview.
I also cant't create new events on google calendars. I have to save it on local calendar and then change the calendar in event window.

**Comment by chad-exc** [comment] 2020-11-14 13:44
@jdigh I am able to write to the calendars at least, thankfully. Have you tried deleting the calender and adding it again?

**Comment by jdigh** [comment] 2020-11-15 15:56
Thanx for support, writing is now possible again after detleting an adding.

Am 14.11.2020 um 14:44 schrieb chad-exc:

**Comment by joek666** [comment] 2020-11-16 16:30
Hi.  On Friday afternoon ~3 days ago) switched the add-on off then back on.  My calendar(s) seem to be working perfectly now.

**Comment by chad-exc** [comment] 2020-11-16 16:58
I can confirm that what @joek666 said seemed to work for me too.

**Comment by jdigh** [comment] 2020-11-16 17:26
I can confirm it too

Am 16.11.2020 um 17:58 schrieb chad-exc:

**Comment by micter59** [comment] 2020-11-16 17:28
It seems ok for me too. So simple ! Should have tought to it before. Thanks !

**Comment by joek666** [comment] 2020-11-16 17:33
I'm the default IT guy where I work.  Like I ask everyone with a computer issue, "Did you reboot your computer"?  99% of the time solves the issue.  The best solution is usually the easiest solution...and I should have taken my own advice before I posted.  Oh well, glad it's working again.  Hope you all have a good one.

**Comment by chad-exc** [comment] 2020-11-16 18:33
@joek666 true! I guess what's weird I would have assumed that by shutting down and restarting thunderbird, it would have had the same effect as disabling/enabling the add-on. But clearly not. Oh well! Good to know this worked.

**Comment by David-R6719** [comment] 2020-11-18 15:15
I am having the same issue with the Google calendar hiding after close.
How am I supposed to disable the add-on when calendar is no longer an add-on.
It is now part of TB. It no longer shows up as Lightning in add-ons.
Thank you

**Comment by mcanonic** [comment] 2020-11-18 15:18
Hi David,
did you already tried to remove the add-on? If yes, does it work?
Best,
Massimo

**Comment by chad-exc** [comment] 2020-11-18 15:24
@David-R6719 it's the provider for google calendar add on your disabling/enabling, not the thunderbird lightning add on.

**Comment by joek666** [comment] 2020-11-18 15:25
In my version of TB the add-on shows up as "Provider for Google Calendar".  It can be found:

TOOLS - ADD-ONS

**Comment by chad-exc** [comment] 2020-11-18 15:27
While all of my calender items show up on startup now thanks to the enable/disable trick, i'm still having two issues. 1.) my calender does not show the correct "current day" (highlighted date) until I restart thunderbird. #2 if I add a new event (or modify a new event), i get the spinning windows 10 "thinking" cursor animation until I switch to a thunderbird fullscreen calendar tab, and then switch back.

**Comment by David-R6719** [comment] 2020-11-18 15:45
I disabled then enabled Provider for Google Calendar. Closed TB. Restarted computer. Seems to have fixed the problem.
I did this before. However, I removed the calendars and re subscribed to them, instead of just disabling the Provider FGC.
Maybe that was a mistake.
Thanks to all that commented! Really appreciate the help!
David 👍

**Comment by joek666** [comment] 2020-11-18 15:52
I am having issues similar to chad-exc.  But, for me, these issues aren't effecting performance of TB or the calendar add-on.

**Comment by chad-exc** [comment] 2020-11-18 16:05
Yeah, those last two specific problems I can't tell if they are provider related or not.

**Comment by David-R6719** [comment] 2020-11-18 16:46
> 
> 
> I disabled then enabled Provider for Google Calendar. Closed TB. Restarted computer. Seems to have fixed the problem.
> I did this before. However, I removed the calendars and re subscribed to them, instead of just disabling the Provider FGC.
> Maybe that was a mistake.
> Thanks to all that commented! Really appreciate the help!
> David 👍

OOPS! I spoke too soon.  It did not solve the problem. Closed TB and reopened it just now and calendars are hidden again!
That fix mentioned above only seems to work temporarily.

**Comment by starwarsfan** [comment] 2020-11-21 09:23
Probably the same as https://github.com/kewisch/gdata-provider/issues/136 ?

**Comment by chad-exc** [comment] 2020-11-21 13:45
Yep @starwarsfan same issue. Also, one thing someone commented on there was that the enable/disable trick only works for a few days. My calendars have gone back to not being visible at startup. (But there have also been Thunderbird updates since then I believe).

**Comment by PHPJJ** [comment] 2020-11-25 19:41
Same issue for me. I have several calenders configured (some public ones) and non of them is visible after startup. I have to disable-enable them every time I start Thunderbird. Version 78.5.0 buildID: 20201116161136.
Pressing [Synchronize] button does nothing.

**Comment by ulda** [comment] 2020-12-13 07:40
I just emerged thunderbird 78.5.1 (64-Bit)
After that, the calendars were not visible on startup.
I had to disable and enable the provider addon (but not removing calendars), after that, the calendars are back visible, even on next startup.
This happend on the last two thunderbird updates I did.

**Comment by fthx** [comment] 2021-01-02 09:37
Since 2 days I use this way my Google calendar:
https://github.com/kewisch/gdata-provider/issues/140#issuecomment-753301708
It does simply work. I do not use advanced features, though, and I don't know if there are caveats.

**Comment by aswinrajeev** [comment] 2021-01-14 04:42
> ### Describe the problem and steps to reproduce it:
> 
> Upgraded to latest version of thunderbird, lightning, and provider. Now I have to unhide all google calendars each time I start Calendars in TB. For some reasons it is automatically hidden at each startup. (I go into lightning calendar tab and toggle eyeballs) I am not sure if it is to do with the add-on or the Calendar feature in TB, but please make sure that the calendar viewing preferences are stored at closing TB.
> 
> Also, when adding a new event, once the event is added, the "thinking" spinning mouse cursor starts going and doesn't stop spinning until I switch to a tab with lightning, and then back to main thunderbird mail layout.
> 
> Running on Windows 10 Pro 1909
> Thunderbird 78.4.3
> Provider 78.0.1

Same here. Every time I have to toggle the visibility for Google Calendar entries to show up.

**Comment by johnk860** [comment] 2021-01-18 23:14
Same problem Different Thread.  Remove Provider for Google, restart Thunderbird, reinstall Provider for Google.  Make sure Provider is in your Add-Ons, if not reinstall again. Enable your Calendars if they indicate disabled,  Close and restart Thunderbird.

**Comment by chad-exc** [comment] 2021-01-18 23:21
@johnk860 So you did the steps below and it works properly now? No more spinning thinking mouse pointer? And even if you reboot thunderbird the changes stick (you don't have to re-enable your calendar each time?)
 
> 
> Same problem Different Thread. Remove Provider for Google, restart Thunderbird, reinstall Provider for Google. Make sure Provider is in your Add-Ons, if not reinstall again. Enable your Calendars if they indicate disabled, Close and restart Thunderbird.

**Comment by johnk860** [comment] 2021-01-19 03:57
I did.  Found a subsequent problem tho, the day after my solution worked and I thought the problem resolved.  I opened T-Bird and ... no calendar.  Had to disable  and re enable (not reinstall) Provider and all came back.  Still a problem.  Not sure whether its Provider or Thunderbird.  I only know that I had to go back to 78.5 to make it go away permanently.  Regrets for offering this solution, but it really looked good for a day.

**Comment by Dolphyn5** [comment] 2021-02-23 19:39
Additional information and workarounds are here: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1677336
https://github.com/kewisch/gdata-provider/issues/159

CalDAV can be used to add a Google Calendar directly to Thunderbird, no need for add-on. 
https://support.mozilla.org/en-US/questions/1261974

**Comment by hannahmetzler** [comment] 2021-03-22 10:19
Did the second problem the initial post mentioned, the mouse cursor starting to spin every time a new event is made in a Google calendar, and not stopping until the calendar tab is closed? I tried to restart, update thunderbird, disable the provider, reinstall the provider, but did not find anything that works so far. At the same time, the red line indicating current time stops to update when this happens. The problem does not happen if I make an event in a different calendar. 
I am on Linux, Kubuntu 20.04, thunderbird 78.7.1 (64-bit), Google provider 78.0.1

**Comment by DomiMooser** [comment] 2021-03-22 10:36
> 
> 
> Did the second problem the initial post mentioned get solved, that is, the mouse cursor starting to spin every time a new event is made in a Google calendar, and not stopping until the calendar tab is closed? I tried to restart, update thunderbird, disable the provider, reinstall the provider, but did not find anything that works so far. At the same time, the red line indicating current time stops to update when the mouse wheel starts to spin, it stays e.g. at 9am until the next time I close and reopen the calendar tab. The problem only occurs with google calendars, not other calendars.
> I am on Linux, Kubuntu 20.04, thunderbird 78.7.1 (64-bit), Google provider 78.0.1
> 
> The same problem has also been reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1681675

I don't think the problem got solved with Provider, but all the problems are solved if you use CalDAV instead of the Provider, it's what I have done and it's rather easy (see link below). :)

**Comment by hannahmetzler** [comment] 2021-03-22 10:52
Thank you so much, that works perfectly!

**Comment by chad-exc** [comment] 2021-03-22 14:34
@DomiMooser Is the CalDAV bidirectional?  Meaning, I can not only view my calendar but I can add events to it via Thunderbird as well?

**Comment by fthx** [comment] 2021-03-22 14:36
Yes of course!
https://github.com/kewisch/gdata-provider/issues/140#issuecomment-753301708

**Comment by hannahmetzler** [comment] 2021-03-22 14:41
Is is also possible to subscribe to other people's calendars via CalDAV? I tried with the public URL to others' calendars, but Google then still asks me to login, and since I don't have there login, enabling the calendar does not work. 
(These do work with google provider, though, since one does not have to add new events to other people's calendars.)
Thank you!

**Comment by fthx** [comment] 2021-03-22 14:52
I don't remember all the story but my wife created a private link to access (read-only) her Google calendar then I included it in TB. It's an ICS format.
I cannot tell your more, sorry.

**Comment by hannahmetzler** [comment] 2021-03-22 14:59
that is already something, thank you!

**Comment by Dolphyn5** [comment] 2021-03-22 15:40
I think you can use CalDAV for any Google Calendar that you have permission to access. At least, it worked for me, read and write.
The Location (URL) should look something like this: https://apidata.googleusercontent.com/caldav/v2/###/events
where ### is replaced by the Calendar ID (including @group.calendar.google.com or @gmail.com or similar).

On the other hand, for the public URL in iCal format, Google says "Warning: The address won't work unless this calendar is public." And when I tried using iCal in Thunderbird, it was read-only.

CalDAV did everything I want it to do, except I haven't found any way to import a task list from Google Calendars.

**Comment by hannahmetzler** [comment] 2021-03-22 16:04
> I think you can use CalDAV for any Google Calendar that you have permission to access. At least, it worked for me, read and write.
> The Location (URL) should look something like this: https://apidata.googleusercontent.com/caldav/v2/###/events
> where ### is replaced by the Calendar ID (including @group.calendar.google.com or @gmail.com or similar).
> 
> On the other hand, for the public URL in iCal format, Google says "Warning: The address won't work unless this calendar is public." And when I tried using iCal in Thunderbird, it was read-only.
> 
> CalDAV did everything I want it to do, except I haven't found any way to import a task list from Google Calendars.

thank you, that did indeed work. No idea why I did not just think about inserting the other person's email (calendar ID). Simple enough :)

**Comment by chad-exc** [comment] 2021-03-22 17:40
> 
> 
> Yes of course!
> [#140 (comment)](https://github.com/kewisch/gdata-provider/issues/140#issuecomment-753301708)

Thanks everyone! CalDav did the trick and no more annoying enabling calendars at start or spinning freeze icon of whenever I add new event!

**Comment by kewisch** [comment] 2021-09-04 23:52
This should be fixed in Thunderbird 91 with the respective Provider

**Closed by kewisch** 2021-09-04 23:52 UTC
