### ISSUE TITLE
Existing repeating events that are distinct (have data for the particular date they relate to,  do not show up with update 78.0.1 

### ISSUE THREAD

**Issue by stevegoodlass** [kewisch/gdata-provider#127] opened 2020-11-04 00:35 UTC
### What happened?
If you had a repeating event with distinct description before the update then when you open the single occurrence of the event after the update, it is empty. However the description appears as it should in calendar.google.com 

Creating a new repeating event and then editing description in a single occurrence works as expected
Creating a new repeating event in calendar.google.com and then saving the description, then checking it again in thunderbird works as expected

Issue seems to be when the repeating events with distinct data for each date occurrence are loaded, they fail to load. 

### Anything else we should know?
Thunderbird 78.4.0
Google provider: 78.0.1

**Comment by heygrasshopper** [comment] 2020-11-25 08:12
I am having the same issue. I have a bi-weekly recurring event, "Payday," with a list of bills to be paid in the notes of each individual occurrence. The notes do not show up in Thunderbird, but do show in Google Calendar.

**Comment by kewisch** [comment] 2021-09-19 17:19
I'm not able to reproduce this for Thunderbird 91. I tried the two cases you suggest work and they work. I tried re-subscribing to calendars, and the exception's notes show up as expected. I'm going to close this issue for now, if it reappears on Thunderbird 91 please re-open

**Closed by kewisch** 2021-09-19 17:19 UTC
Labels: investigate
