### ISSUE TITLE
i can see the calenders but have to make them visible every time i open tb

### ISSUE THREAD

**Issue by glda19** [kewisch/gdata-provider#136] opened 2020-11-17 17:57 UTC
### Describe the problem and steps to reproduce it:

(Please include as many details as possible.)

### What happened?
I have many callendars in tb. I can see tem. 
After clossing and reoping tb i have to make te callendars visible so i can se the entrys

### What did you expect to happen?
But wen i close tb and reopen all the callender entrys's are not visible.

**Comment by hans109h** [comment] 2020-11-19 00:07
I can confirm this is happening.  I subscribe to a Google Calendar and in order to see the calendar events I have to cycle the calendar from visible to not visible and back on every Thunderbird start.  I haven't determined yet if this is affecting notifications.

The expected behavior is that the events of a calendar set to be visible are displayed on the calendar when the program starts.  
The actual behavior is that the events of a Google Calendar set to be visible are not displayed on the calendar until the visibility of the calendar has be cycled.

**Comment by hans109h** [comment] 2020-11-19 00:12
I'm seeing now this is a duplicate of other bugs reported.  I have solved my problem by temporarily disabling the Provider extension and then re-enabling.  After re-enabling the calendars display as expected.

**Comment by starwarsfan** [comment] 2020-11-21 09:19
I spot the same issue and cannot resolve it as the comment before suggested. I disabled the extension, shutdown TB, restart TB, enabled the extension and activated the Google calendars. But the behaviour is the same. 

After restart of TB, the calendars are invisible, even if the eye-icon states, that they should be visible. So I need to make every calendar invisible by clicking once on the eye icon and then click again to make it visible. Now the calendar appears.

**Comment by mcanonic** [comment] 2020-11-21 09:30
The disable-enable trick works only for one (or two) day(s).
Something different is necessary.
Does this extension update automatically?
M

**Comment by wagenaar** [comment] 2020-11-21 18:57
I am having the same issue.  Calendar postings will not show unless I click hide and unhide for each calendar.  Disabling and re-enabling the Provider extension doesn't seem to do anything for long.  I don't understand the technical side, but it _appears_ that there is no refresh of the calendars occurring to pull in the individual postings for each calendar.  Thank you.

**Comment by eslothouber** [comment] 2020-11-24 13:25
After shutting down Thunderbird I have to click all the visibility buttons twice for all my google calendars to show up. Dis- and re-enabling the provider works for a day.
Hope this gets solved, thanks in advance!

**Comment by smithxl** [comment] 2020-11-25 14:45
After disabling and enabling Provider the order of my calendars is changed. I can find no way to re-order them other than by dragging each one into place every time this happens. The alternative, hiding then showing each calendar in turn, is just as laborious.

I guess that the fault lies with Thunderbird but the task of dealing with it is left to the addon developer ...

**Comment by EKatowitz** [comment] 2021-01-08 12:50
This issue is still occurring for me.    Everytime I launch TB I have to go into Calendars and make each one visible again.

Is this a TB issue or an issue with this add-on?

**Comment by Bushy2006** [comment] 2021-01-30 10:34
I can confirm that this bug only affects some installations. My wife has the problem on all calendars but I don't. We access the same calendars. Most are on google accounts I have and share with her read-only, one is a shared account for which we both have read-write access and one is her own account that she shares with me as read-only.

**Comment by maxh77779** [comment] 2021-02-02 03:04
This is still an issue - it affects my wife and my shared calendars, and is very annoying. I've tried disabling and re-enabling the add-on, reinstalling the add-on and more, and it keeps happening almost every time I go to access the list of calendars. I'm using the latest version of the add-on and TB (78.7.0). Has anyone found any more info about this? It's an issue for all 3 of our machines - my wife's laptop, my laptop and my desktop, so I'm wondering if it's something specific to our setup. But it always used to work before??

**Comment by Bushy2006** [comment] 2021-02-02 08:34
I did see a comment on another forum saying that if you close the calendar tab before closing Thunderbird, calendars show as normal when you re-open Thunderbird then the calendar tab.

**Comment by glda19** [comment] 2021-02-02 11:11
Yes and ?

⁣BlueMail voor Android downloaden ​

Op 2 feb. 2021 09:34, om 09:34, Bushy2006 <notifications@github.com> schreef:

**Comment by kewisch** [comment] 2021-09-04 23:29
I believe this was fixed in Thunderbird in the meanwhile. Please upgrade to Thunderbird 91 and try again.

**Closed by kewisch** 2021-09-04 23:29 UTC
