### ISSUE TITLE
Dismissing Reminders not created by me returns 403

### ISSUE THREAD

**Issue by vogthenn** [kewisch/gdata-provider#572] opened 2023-01-24 09:35 UTC
### Describe the problem and steps to reproduce it:
Let someone else invite you to a meeting with a reminder.  Dismissing this reminder will be impossibe.

I can't find the message anymore, but it said somewhere that I tried to modify attributes that I'm not allowed to modify, because I'm not the owner of the meeting.  I could not find a notification of this in other bugs (there are many regarding this), so I created a new bug.

### What happened?
Reminder pops up, but I can't dismiss it (XXed out some ids):
`POST`  `https://www.googleapis.com/calendar/v3/calendars/XXX@XXX.com/events/XXXXXXXXXXXXXa_R20221122T090000`

(POST request is sent, but in the headers I can see `X-HTTP-Method-Override: 	PUT`, could be the problem, maybe?)

POST Body:

    {"start":{"dateTime":"2022-11-22T10:00:00","timeZone":"Europe/Berlin"},"end":{"dateTime":"2022-11-22T10:45:00","timeZone":"Europe/Berlin"},"summary":"Founder Team - Regular","description":"Regular meeting with updateds and plans for the week.","status":"confirmed","reminders":{"overrides":[],"useDefault":true},"extendedProperties":{"private":{"X-MOZ-LASTACK":"2023-01-24T09:18:38Z"}},"recurrence":["RRULE:FREQ=WEEKLY;BYDAY=TU","EXDATE:20221227T090000Z","EXDATE:20230103T090000Z","EXDATE:20230110T090000Z","EXDATE:20230117T090000Z"]}

Response:
`calGoogleCalendar] Modifying item Founder Team - Regular failed:2147500037: `

     { "error": {  "errors": [   {    "domain": "global",    "reason": "forbidden",    "message": "Forbidden"   }  ],  "code": 403, "message": Forbidden"  }}

### What did you expect to happen?
Reminder should be closed and not pop up again.

### Anything else we should know?
I'm developer myself, I hope this is enough data to fix this better, if not, sorry for spamming the bug list.

**Comment by peci1** [comment] 2023-02-03 08:19
This is a duplicate of https://github.com/kewisch/gdata-provider/issues/3.

The issue has already been fixed two years ago, but the fix has not been released yet: https://github.com/kewisch/gdata-provider/issues/3#issuecomment-913054718 . This is a very unfortunate situation... @kewisch can't you ask the TB addons team to help you with the required changes?

**Comment by dlech** [comment] 2023-02-10 16:10
The patch from https://github.com/kewisch/gdata-provider/issues/3#issuecomment-1323832877 seems to fix the problem for me. I just manually edited the file in the local install of the extension.

**Comment by kewisch** [comment] 2023-07-08 19:48
Indeed #3. As mentioned there this is fixed on the main branch. Porting the change correctly would be quite a bit of work. The simple patch might be a bit too simple, I have the feeling there might be some edge cases that don't work that way (e.g. secondary calendars). I'm not opposed if someone wants to go through the effort of testing all the edge cases, but I'd like to avoid putting in more work than compat updates into the legacy branch.

**Closed by kewisch** 2023-07-08 19:48 UTC
