### ISSUE TITLE
Event updates and cancellations fail with status 80004005

### ISSUE THREAD

**Issue by henning** [kewisch/gdata-provider#449] opened 2022-06-01 11:33 UTC
### Discussed in https://github.com/kewisch/gdata-provider/discussions/444

<div type='discussions-op-text'>

<sup>Originally posted by **henning** May 24, 2022</sup>
Opening this as a bug as I received no answer in discussion so far, and experienced it many times in the meantime:

I have got a mail for a change to a repeating event.

The diff is displayed nicely as expected, and I am offered a button to "accept all" 

On pressing that button, i get a popup window saying:

Processing message failed. Status: 80004005.

Is there anything i can do?

Version information:

Thunderbird 91.9.1 on Ubuntu 22.04
Google Calendar provider 102.0.0

Let me know if there is any further info required to help getting this solved.</div>

Addition: 

I also received a few Event cancellation mails in the meantime, where clicking on "delete" leads to the same message being shown.
Expected behaviou would be to delete the canceled events, but they keep unchanged.

**Comment by walterzanette** [comment] 2022-06-06 08:56
Almost the same issue here:

Thunderbird 91.10.0 on Win 10 Pro
Google Calendar provider 102.0.0

When an event is sent from Microsoft Teams it is correctly added to the google calendar, but if the sender sends an update a 

**Processing message failed. Status: 80004005.**

appears and the event is not modified.

From the console I see the following:

![Pic1](https://user-images.githubusercontent.com/104968478/172126818-9939a9cc-2238-4745-a22f-11ff57b96604.jpg)
![Pic2](https://user-images.githubusercontent.com/104968478/172126834-d4ecc24e-d5bf-4328-afb4-11a49f6fa48d.jpg)

Additional info:
-Everything works fine if I receive the invitation and the updates from a google account
-The issue is the same either for a single event or for an event with repetition

**Comment by unode** [comment] 2023-08-15 12:20
I'm experiencing this issue as well. It seems to happen more frequently when the invite involves or was sent by participants from outside the organization.

In some cases restarting Thunderbird works around the error.
In this case the event is typically displayed as "Event has been processed" but it is not clear why this works and what causes the error in the first place. Manually synchronizing involved calendars doesn't seem to help either.

**Comment by kewisch** [comment] 2023-10-15 20:11
This is unfortunately a variant of #3. I might get around to providing a better solution for this, I would have hoped to do this by completing the the non-legacy version, but I've been saying that since 2 releases. Given I know the root cause and it very much is on my radar I'm going to close this issue, but I appreciate that you are reporting it. It is fixed in the non-legacy version, but that version is far from usable.

**Closed by kewisch** 2023-10-15 20:11 UTC
