### ISSUE TITLE
New event spining wheel

### ISSUE THREAD

**Issue by smithxl** [kewisch/gdata-provider#175] opened 2021-03-27 08:58 UTC
Thunderbird updated automatically to latest version. Provider for Google Calendar ditto.

When I add an event and click Save and Close the spinning wheel appears and never stops, unless I click on another tab e.g. Inbox or Add-ons Manager (if open) and then click back on Calendar. After that all is well. I can also close Thunderbird and reopen it - the new event is there and all is well.

I can edit an existing event without the spinning wheel starting.

However I open the Edit item box the same happens. With the box open, I can Ctrl S or click Event Save and when I try to close the box I am told it has not been saved.

**Apart from this issue, all is working exactly as I would expect.**

Modest customisation via userChrome.css file. (Tried deleting userChrome file and restarting, issue not affected).
Seven Google calendars synchronised. Only Holidays in the UK is read only (default).
Custom calendar colours chosen via Properties.

**Comment by Janoo1606** [comment] 2021-05-16 02:34
Same problem.
I would be very happy about a solution.

**Comment by tommyguard3** [comment] 2021-05-26 15:50
Also having the same problem, cannot find any work around.  Thank you.

**Comment by michaelfalling** [comment] 2021-06-14 14:39
I am having the same problem the spinning wheel not a big issue but just annoying, as mentioned before as soon as you leave the calendar tab the issue is resolved and all is normal, the synchronisation really does work well.

Provider for Google Calendar Version 78.0.1
Thunderbird (Windows) Version 78.11.0 (64-bit)

**Comment by kewisch** [comment] 2021-09-13 08:06
This should be resolved in Thunderbird 91 with the latest version of the Provider. Please reopen if not the case.

**Closed** 2021-09-13 08:14 UTC
