### ISSUE TITLE
Google calendar does not sync anymore with Thunderbird 78.5.0

### ISSUE THREAD

**Issue by chkug** [kewisch/gdata-provider#140] opened 2020-11-27 18:35 UTC
After upgrading my mail client to Thunderbird 78.5.0 the synchronization of one of my Google calendars does not work anymore. I would be very grateful for helpful hints.

**Comment by bennybubble** [comment] 2020-11-28 19:35
Same issue here, initially (after setup) it loads all items from google calendar but after restarting TB, it doesn't load them anymore.
Using TB 78.5.0 and Provider for Google Calendar 78.0.1

-ben

**Comment by jbnetwork** [comment] 2020-11-28 22:29
Having similar issues. Notice the calendars come back after I hide then unhide. But they go away again after restart so I have to again hide and unhide. Running 78.5 w/Provider 78.0.1

**Comment by bennybubble** [comment] 2020-11-30 10:30
> Same issue here, initially (after setup) it loads all items from google calendar but after restarting TB, it doesn't load them anymore.
> Using TB 78.5.0 and Provider for Google Calendar 78.0.1
> 
> Removing / re-installing the Provider-for-Google-Calendar add-on did not help!
> 
> -ben

Could it be related to the number of items in a particular calendar?
Mine calendar has over 600 items (mostly historical items that I need to keep), that won't show up in TB, while a newly created calendar will appear (also after restarting) all the time!

-ben

**Comment by bennybubble** [comment] 2020-11-30 11:07
> > Same issue here, initially (after setup) it loads all items from google calendar but after restarting TB, it doesn't load them anymore.
> > Using TB 78.5.0 and Provider for Google Calendar 78.0.1
> > Removing / re-installing the Provider-for-Google-Calendar add-on did not help!
> > -ben
> 
> Could it be related to the number of items in a particular calendar?
> Mine calendar has over 600 items (mostly historical items that I need to keep), that won't show up in TB, while a newly created calendar will appear (also after restarting) all the time!
> 
> -ben

Please find the requested debug file, looks like a problem with *item.startDate is null* but I am not able to solve this :-(

![image](https://user-images.githubusercontent.com/1083428/100602671-7f168480-3304-11eb-8d77-17a809899624.png)

-ben

**Comment by chkug** [comment] 2020-11-30 11:13
I think I was able to solve my problem now after all: I logged off the affected calendar under Thunderbird and then logged it back on (with the data I could find out from the Google calendar on the internet). After that, everything was really alright again. Let's hope it stays that way.

**Comment by bennybubble** [comment] 2020-11-30 11:28
> I think I was able to solve my problem now after all: I logged off the affected calendar under Thunderbird and then logged it back on (with the data I could find out from the Google calendar on the internet). After that, everything was really alright again. Let's hope it stays that way.

Good to hear, tried *EVERYTHING* what has been suggested but no way to load the calendar into TB. The only time I see it is after subscribing to it and after restart TB it is gone again .... 
Driving me nuts ....

**Comment by chkug** [comment] 2020-11-30 12:15
I'm sorry about that! My solution does not work for you either?

**Comment by bennybubble** [comment] 2020-11-30 12:18
> I'm sorry about that! My solution does not work for you either?

Unfortunately not.

**Comment by Tripp339** [comment] 2020-11-30 19:10
I'm having the same issue. TB 78.5.0 (64-bit), GProvider ver 78.0.1. Cannot add attendees to events and have them saved and written to Google.

**Comment by loelschlaeger** [comment] 2020-12-02 16:45
Same issue now also with TB 78.5.1 (64-bit), GProvider ver 78.0.1.

**Comment by ytdlder** [comment] 2020-12-07 06:00
I have to second that... not working anymore with TB 78.5 :-(

**Comment by ChicagoJay** [comment] 2020-12-09 20:52
Same problem here.  Windows 10 20H2, TB 78.5.1 x64, GDP 78.0.1 and I have to hide/unhide my calendars in order to see them.

**Comment by chrismox** [comment] 2020-12-10 15:32
Same here, TB 78.5.1.
Hiding and unhiding works.

**Comment by bennybubble** [comment] 2020-12-10 15:47
Hiding / unhiding does not work for my.
Only remove and adding the Google Calendar will show it but that is not the intention I think :-)

**Comment by Tripp339** [comment] 2020-12-10 16:42
Is anyone downgrading to a previous version of TB?

**Comment by Tripp339** [comment] 2020-12-10 16:46
What about invitations not working?

**Comment by lucknaumann** [comment] 2020-12-21 02:50
I had this issue, too. TB just updated to 78.6.0 and all Calendars appear to be working. Weird. Provider for Google Calendar = 78.0.1.

**Comment by ChicagoJay** [comment] 2020-12-21 13:55
It's been working for the last couple of days for me too, and I
    didn't update TBird until just now, so it was working again under
    78.5.1 as well.  Weird indeed.
    --
Jay Duff, CCE, ACMT, ACiT
Network Specialist
Mannheim School District 83
Franklin Park, IL
    On 12/20/2020 8:50 PM, lucknaumann
      wrote:
    
    
      
      I had this issue, too. TB just updated to 78.6.0 and all
        Calendars appear to be working. Weird. Provider for Google
        Calendar = 78.0.1.
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kewisch/gdata-provider/issues/140#issuecomment-748727318",
"url": "https://github.com/kewisch/gdata-provider/issues/140#issuecomment-748727318",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Tripp339** [comment] 2020-12-21 14:25
Invitations are still not working.  I removed and re-installed the Provider.  Still no success.

**Comment by wosym** [comment] 2020-12-30 12:33
Last week I started experiencing the same issue as described here. After updating Thunderbird to 78.6.0 (as was suggested here, or elsewhere) the problem ceased to exist: all events from all calendars are visible by default. 

However, this morning the bug appears to be back again, without me having taking any action? I have to disable and reënable the calendars.

**Comment by Tripp339** [comment] 2020-12-30 15:25
Has anyone heard anything from the developer?

**Comment by fthx** [comment] 2021-01-01 11:00
I've just moved from Gdata Provider to **CalDAV** use because it's a 6 months old issue, so...
Easy and seems to work flawlessly. Not a hack.

**Source:**
https://support.mozilla.org/en-US/questions/1261974

**To do:**
0) Enter Thunderbird's calendar tab.
1) Add a new calendar.
2) Select Network then CalDAV.
3) Enter your Google username (not the email).
4) Enter the main Google calendar address: https://apidata.googleusercontent.com/caldav/v2/*****************/events replacing the stars with your Gmail address (e.g. no_more.covid@gmail.com).
5) If you want to add some other Google calendars (external, secondary, etc.), go to your Google Calendar webpage then enter the properties of the calendar to be included, then catch its Calendar ID and replace the stars in 4) with this ID.
6) Thunderbird will ask your Google credentials to access your calendars ("Lightning" will access them).

**Comment by Wheatleybloke** [comment] 2021-01-13 08:22
Similar issues wit latest versions of TB and Provider. Traced to issues with series of repeated events. If I set up a series of events in Gmail calendar itself, the series is synchronised to my Android phone and TB. It I delete one event from the series using my phone it does not get synchronised to TB which goes into a waiting loop, Likewise if I delete one event from a series in TB it does not synchronise eleswhere. ie it seems Google Calendar must insert some sequence code that it is happy to work round itself. If I export the GC to Caldav, it can see error code for the cancelled events.
This has only happened since November

**Comment by Wheatleybloke** [comment] 2021-01-14 08:00
More investigation: If I create in TB a recurring weekly event say "Misic Lesson" at 10am Wednesday from 6th January for 10 weeks the series syncs across all devices and platforms (Windows, Linux, Android, Google). If I delete or change a date or time outside of TB (ie in Google calendar) Google offers to changes the "rest of" series to run that date and time TB can't accept that and still sees the original series from 6th Jan. I can cancel the individual date of time, but it does not get synchronised or else gets synchronised as a a new event

**Comment by jbenden** [comment] 2021-01-22 23:15
On 78.6.1 the extension was "broken" with my existing settings. I got it working by enabling cookies (w/o third-party ones, though).

**Comment by ecollart** [comment] 2021-01-26 09:06
Unfortunately having to add to that problem.

In my case, the Google calendars are just not showing up after a while (like if I hide them). Hiding then unhiding shows the calendars back. Not sure about sync problem or not but creating a new event seems to work but the hourglass appears forever until I click on another tab and come back in the agenda tab.
If I start in safe mode then come back as normal, the calendars are showing up again for a while.
I use TB 78.6.1 32 bits in French and module 78.0.1 on Windows 10. Same problem seen on my partner's laptop (same config).

VERY annoying bug to work with ...

Joining TB Troubleshooting info here if of any help

[TB.pdf](https://github.com/kewisch/gdata-provider/files/5872254/TB.pdf)

Thanks for your help and support !

Eric

**Comment by Wheatleybloke** [comment] 2021-01-26 10:26
Same issue as ecollart just started. Added a new calendar feed in Google and all my calendars disappeared in TB. I had to hide all calendars and then unhide to see them again.

**Comment by fthx** [comment] 2021-02-08 20:35
Just to mention that TB 78.7.1 officially supports Google contacts:
https://www.googleapis.com/carddav/v1/principals/<userEmail>
to add as Cardav address book (to be eventually activated in config editor ie advanced settings).

I use https://github.com/kewisch/gdata-provider/issues/140#issuecomment-753301708 since some time now and I get no issue, at least with a basic usage (creating, deleting, moving events).

**Comment by ytdlder** [comment] 2021-02-09 05:32
Ty for mentioning that!

**Comment by elhennig** [comment] 2021-02-11 11:41
I only have a problem with a series of entries that I modified (and they are actual in Google calendar) but the changes of the single series entries does not sync to the TB calendar. Looks to be as if this is a kind of caching problem.
Unsubscribing the calendar and readding it works for the current session, but after a restart of TB the cached and outdated version of the entries appears again.

**Comment by sdungs-li** [comment] 2021-03-03 15:14
Hey, I have been experiencing the same issue (had to hide/unhide all calendars after each program start to make them display) and saw this comment in the reviews of the "provider for google calendar" add-on:

>  by Firefox user 8d765d on Feb. 17, 2021 · permalink
> 
> I was really annoyed - I use Thunderbird 78.7.1 for Mac and the AddOn in version 78.0.1. I use various Google calendars both privately and professionally, all of which I had integrated during the initial setup. After restarting Thunderbird, the programme no longer displayed any calendar contents, only a constantly "busy" cog was turning. Calendars were listed but had no content. In the forums mostly desperate people wanted to go back to TB 68.
> My solution: deactivate "Provider for Google Calendar" in the Thunderbird AddOns (do not uninstall). There is then a prompt asking whether the calendars should all be de-registered - I cancelled this, but the whole thing was then deactivated anyway (seemed like a bug to me). Then activate the add-on again with the slide switch - the contents of the calendars are displayed again. Now restart Thunderbird completely - then everything works fine. Somehow the add-on needed a kind of restart.

This did work for me! I tried restarting TB a couple of times now and calendars display right from the beginning!

**Comment by Wheatleybloke** [comment] 2021-03-03 16:51
Similar issues since moving from 68.0. Calendars just disappear en mass. Hide and view brings them back, but no pattern to loss; can be stable for days and then just vanish. I have just noticed in TB 78.7.1 that when ever I create or alter an event, the working cog just goes round and round until I switch to mail and back
@elhennig: same issue with altering any series. Sometimes the whole series just disappears. If I change the series in Google and then look in TB, I can see the alterations don't match.eg: if I alter "This and all later events" in Google, the series start date is redefined, but in TB the original start date is hung onto so is completely out of sync.

**Comment by lucknaumann** [comment] 2021-03-03 19:10
Yeah, I got fed up with this add-on's on-again, off-again relationship. Moved on to the Open Google Calendar add-on. Works great. On another computer, I didn't recall the name and installed GCalTab. Works great, too.

**Comment by Wheatleybloke** [comment] 2021-03-03 19:26
@lucknaumann: Many thanks. Can't believe how simple this was. I've been waiting since TB 71 for this advice

**Comment by lucknaumann** [comment] 2021-03-03 20:23
@Wheatleybloke You're welcome! Yeah, I couldn't believe I found those add-ons, either. They function the same way and are essentially the same add-on. 😆

**Comment by tperk100** [comment] 2021-03-05 21:03
Sami issues with me.

**Comment by fthx** [comment] 2021-03-09 08:31
Saw this in 78.8.1 release notes:
![image](https://user-images.githubusercontent.com/23138504/110441387-015bd500-80ba-11eb-8aaa-215c130a4ce6.png)
Don't know if this will solve the issue.
(Remember, you can sync Google Calendar without any add-on: https://github.com/kewisch/gdata-provider/issues/140#issuecomment-753301708)

**Comment by tperk100** [comment] 2021-03-09 10:35
fthx,
Thanks, just tried it again and it seems to be working (at least for last 10 minutes), both calendar and tasks.

**Comment by ImmanuelHaffner** [comment] 2021-03-11 09:33
I can confirm that upgrading TB from `78.7.1` to `78.8.1` resolved the issue of invisible calendar events at launch.  (I switched to CalDAV anyways.)

**Comment by Oliwally** [comment] 2021-06-14 11:36
I am still having issues with .ics calendars from google in version 78.11. The calendar links are provided by my workplace, both .ics.
They both used to work (read only of course). Now only one works and the other just will not show. No idea what's going on.

**Comment by chimicus** [comment] 2021-07-26 09:46
I have never used it before 78.11 and in this version it doesn't work. I simply installed the extension, went to calendar, checked my email was correct and clicked synchronize. Nothing happened.

Happy to give more details if needed.

**Comment by Oliwally** [comment] 2021-07-26 22:06
I managed to resolve my issue by installing the Provider for Google Calendar extension & logging into my workplace account. This should not have been needed for a simple subscription, but hey...
I am thinking that perhaps someone at my workplace did change the permissions of that google calendar so that it now requires login. In any case, the extension solved my problem.

**Comment by fthx** [comment] 2021-08-10 10:09
FYI Thunderbird 91 beta handles Google Contacts & Calendar natively. You chose your subscriptions at account creation.
It works, as far as I tested.
Uses carddav and caldav, as I did before manually.

**Comment by kewisch** [comment] 2021-09-04 23:28
Issues around invitations are covered in another issue. I'm not quite sure what the concrete issue is in this issue, it seems the original issue stopped appearing eventually? I'm closing for now, please re-test in Thunderbird 91.

**Closed by kewisch** 2021-09-04 23:28 UTC

**Comment by camueller** [comment] 2023-01-06 18:52
> I've just moved from Gdata Provider to **CalDAV** use because it's a 6 months old issue, so... Easy and seems to work flawlessly, and obviously allows to read _and_ write your calendar. Not a hack.

Did the same with your step-by-step guide after the add-on stopped working. Works perfectly now without any add-on. Thank's a lot for this guide.
