### ISSUE TITLE
Provider keeps removing all attendees from events

### ISSUE THREAD

**Issue by jaymzh** [kewisch/gdata-provider#138] opened 2020-11-18 19:28 UTC
### Describe the problem and steps to reproduce it:

This took a while to track down, but it seems the provider keeps removing all attendees from my recurring meetings.

It seems to happen when I "dismiss" reminders.

I downloaded all the logs from our Google Domain account and saw that the deletions were happening through the API, so I set my calendars to RO in Thunderbird and the problem stopped. After 2 weeks I set it back to RW, and the problem started up again. The logs correlate.

### What happened?

My recurring events lose all their attendees.

### What did you expect to happen?

It to not change the attendees

### Anything else we should know?

Version 78.0.1

**Comment by tomaslledo** [comment] 2020-11-19 14:33
I have the exact same problem. Thanks for posting it; I'll arrange it as RO in my Thunderbird as well. Let's hope they find what's happening.

**Comment by unode** [comment] 2020-11-23 22:39
Looks like a duplicate of #103

**Comment by tomaslledo** [comment] 2020-11-24 10:47
> 
> 
> Looks like a duplicate of #103

Yes, I had a look at the issue you suggest, and the problem is the same. The original issue was similar but not the same; later, some people added comments with the same problem.

Thanks for pointing it out.

**Comment by twain28** [comment] 2020-11-26 10:10
This is probably related to the new syntax for gcals, and is perhaps linked to the fact that you cannot choose the the email account to confirm or reject an invitation.
I actually noticed this seems also to occurr when you "delete" an alarm...it deletes the whole event for everyone else but you...and syncs it online!

**Comment by roccopietrini** [comment] 2020-11-26 11:53
It's als a duplicate of [this](https://github.com/kewisch/gdata-provider/issues/129)

I can confirm what @twain28  says. Deleting or snoozing alarms remove all attendees, so the event disappear from their calendar instantly! Only workaround at the moment is to set the calendar in read-only mode in thunderbird!

**Comment by Tripp339** [comment] 2020-11-30 18:55
I'm having the same issue. TB 78.5.0 (64-bit), GProvider ver 78.0.1. Cannot add attendees to events and have them saved and written to Google.

**Comment by MelvinRook** [comment] 2020-12-15 11:05
The key trigger for this bug is `"It seems to happen when I "dismiss" reminders"`. Especially with recurring events, it's a large issue, because all attendees are removed from all events.

**Comment by Tripp339** [comment] 2020-12-21 14:34
...and the issue continues.  I just tried to add attendees.  Still not working.  Removed and re-installed the Provider.  No change.  TB Ver 78.6.0 Provider Ver 78.0.1

**Comment by sei-nicolas** [comment] 2021-01-01 14:46
I did some verifications and the root cause is here: https://github.com/kewisch/gdata-provider/blob/0d41a4193fc12b6f9a4a6dd09cc7968f27fccd15/src/legacy/modules/gdataUtils.jsm#L369

Attendees for an event will not be parsed (hence saved/updated, and will even disappear at any POST for a given event) unless the option is specifically activated.

Reasons for that specific option are detailed in https://bugzilla.mozilla.org/show_bug.cgi?id=400808

I did not try to reproduce on my side yet, but TLDR seems to be that unwanted invitations may be sent to attendees because of interactions between Google Calendar & local calendar (hence might be risky to activate attendees management!).

Also, as mentioned in other comments, this issue is directly related with #129, #121 and #103

**Comment by yongkhun** [comment] 2021-01-25 02:50
> 
> 
> I did some verifications and the root cause is here:
> 
> https://github.com/kewisch/gdata-provider/blob/0d41a4193fc12b6f9a4a6dd09cc7968f27fccd15/src/legacy/modules/gdataUtils.jsm#L369
> 
> Attendees for an event will not be parsed (hence saved/updated, and will even disappear at any POST for a given event) unless the option is specifically activated.
> 
> Reasons for that specific option are detailed in https://bugzilla.mozilla.org/show_bug.cgi?id=400808
> 
> I did not try to reproduce on my side yet, but TLDR seems to be that unwanted invitations may be sent to attendees because of interactions between Google Calendar & local calendar (hence might be risky to activate attendees management!).
> 
> Also, as mentioned in other comments, this issue is directly related with #147, #129, #121 and #103

Good catch. I tried to manually added the preference "calendar.google.enableAttendees" with true value in Config Editor and it works. The attendees won't be removed anymore when any event reminder is dismissed, until you restarted Thunderbird. Every time Thunderbird is restarted, this manually-added preference will always be removed... Any help?

**Comment by humbertleonardo** [comment] 2021-04-28 12:15
> > I did some verifications and the root cause is here:
> > https://github.com/kewisch/gdata-provider/blob/0d41a4193fc12b6f9a4a6dd09cc7968f27fccd15/src/legacy/modules/gdataUtils.jsm#L369
> > 
> > Attendees for an event will not be parsed (hence saved/updated, and will even disappear at any POST for a given event) unless the option is specifically activated.
> > Reasons for that specific option are detailed in https://bugzilla.mozilla.org/show_bug.cgi?id=400808
> > I did not try to reproduce on my side yet, but TLDR seems to be that unwanted invitations may be sent to attendees because of interactions between Google Calendar & local calendar (hence might be risky to activate attendees management!).
> > Also, as mentioned in other comments, this issue is directly related with #147, #129, #121 and #103
> 
> Good catch. I tried to manually added the preference "calendar.google.enableAttendees" with true value in Config Editor and it works. The attendees won't be removed anymore when any event reminder is dismissed, until you restarted Thunderbird. Every time Thunderbird is restarted, this manually-added preference will always be removed... Any help?

Were you able to make this modification the default?

**Comment by humbertleonardo** [comment] 2021-04-28 13:26
> > I did some verifications and the root cause is here:
> > https://github.com/kewisch/gdata-provider/blob/0d41a4193fc12b6f9a4a6dd09cc7968f27fccd15/src/legacy/modules/gdataUtils.jsm#L369
> > 
> > Attendees for an event will not be parsed (hence saved/updated, and will even disappear at any POST for a given event) unless the option is specifically activated.
> > Reasons for that specific option are detailed in https://bugzilla.mozilla.org/show_bug.cgi?id=400808
> > I did not try to reproduce on my side yet, but TLDR seems to be that unwanted invitations may be sent to attendees because of interactions between Google Calendar & local calendar (hence might be risky to activate attendees management!).
> > Also, as mentioned in other comments, this issue is directly related with #147, #129, #121 and #103
> 
> Good catch. I tried to manually added the preference "calendar.google.enableAttendees" with true value in Config Editor and it works. The attendees won't be removed anymore when any event reminder is dismissed, until you restarted Thunderbird. Every time Thunderbird is restarted, this manually-added preference will always be removed... Any help?

I managed to make this modification the default, but Thunderbird does not send an invitation notification, do you know how to resolve it?

**Comment by jaymzh** [comment] 2021-04-28 16:08
Hmmm. That code was added _7 years_ ago, but gdata was working well for me until late last year. Are we sure that code is the actual problem? Or is it possible enabling that just works around another bug. Or, more to the point, when you enable that, does it bring back the original bug that was added to fix (accepting an invite re-invites all attendees)?

**Comment by humbertleonardo** [comment] 2021-04-29 13:50
I wrote the step by step of my resolution in #147

**Comment by kewisch** [comment] 2021-09-04 23:40
I've identified the cause for this issue, I believe there is another ticket open to cover it. I'll be fixing this for Provider 91.0.2

**Closed by kewisch** 2021-09-04 23:40 UTC
