### ISSUE TITLE
Provider deletes event attendees from event, and removes event from their calendars

### ISSUE THREAD

**Issue by reblake** [kewisch/gdata-provider#184] opened 2021-05-20 13:49 UTC
### Describe the problem and steps to reproduce it:
Problem: 
Event attendees are removed from event, and the event is removed from their calendar when Thunderbird event reminder is either snoozed or dismissed.  

Steps to reproduce problem:
 - create event in Google Calendar in web browser and invite guests/attendees
 - synchronize calendars in Thunderbird, so event shows up (calendar must _not_ be read-only)
 - snooze or dismiss the event reminder

### What happened?
Initially, colleagues for whom I would set up a Zoom meeting would notice the meeting had disappeared from their calendar just before the meeting.  They were confused as to whether I had cancelled the meeting or not.  I had _not_ cancelled it, and it still appeared on my calendar as expected.  

I contacted my organization IT dept, as they manage the organization's GSuite and Zoom subscriptions.  They thought it was a Zoom problem, so spent months with Zoom support trying to figure it out. 

Further troubleshooting and test events revealed it also happened for non-Zoom events, and looking at the calendar logs reveled that it was Thunderbird deleting the attendees and the events from the attendees' calendars.  

### What did you expect to happen?
I expected invited attendees to still see the event in their calendars, and still be invited to the event, regardless of what I do to my Thunderbird reminders.  

### Anything else we should know?
Thunderbird 78.10.2, release channel
Provider 78.0.1, auto updates (last update Sept 2020)

### Error Console messages
NS_ERROR_NOT_AVAILABLE: PreferDisplayName: undefined - not a boolean AddrBookCard.jsm:197
    getPropertyAsBool resource:///modules/AddrBookCard.jsm:197
NS_ERROR_NOT_AVAILABLE: 2 ActivityManager.jsm:127
    getActivity resource://gre/modules/ActivityManager.jsm:127
    removeActivity resource://gre/modules/ActivityManager.jsm:80
    onFolderRemovedFromQ resource:///modules/activity/autosync.jsm:244
    _timerCallback resource:///modules/AppIdleManager.jsm:30
NS_ERROR_NOT_AVAILABLE: 2 ActivityManager.jsm:127
    getActivity resource://gre/modules/ActivityManager.jsm:127
    removeActivity resource://gre/modules/ActivityManager.jsm:80
    onFolderRemovedFromQ resource:///modules/activity/autosync.jsm:244
NS_ERROR_NOT_AVAILABLE: ActivityManager.jsm:127
    getActivity resource://gre/modules/ActivityManager.jsm:127
    removeActivity resource://gre/modules/ActivityManager.jsm:80
    onFolderRemovedFromQ resource:///modules/activity/autosync.jsm:244
    _timerCallback resource:///modules/AppIdleManager.jsm:30
Lightning: [calGoogleCalendar] 2021-05-20T09:00:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-20T09:15:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-19T14:00:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-19T15:00:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-19T17:00:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-19T17:15:00-04:00 does not match timezone offset for America/New_York 2 gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-19T17:30:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-20T09:30:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-20T09:45:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-20T09:00:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-20T09:15:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-20T09:30:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
Lightning: [calGoogleCalendar] 2021-05-20T09:45:00-04:00 does not match timezone offset for America/New_York gdataUtils.jsm:265
NS_ERROR_NOT_AVAILABLE: PreferDisplayName: undefined - not a boolean 2 AddrBookCard.jsm:197
    getPropertyAsBool resource:///modules/AddrBookCard.jsm:197
NS_ERROR_NOT_AVAILABLE: 2 ActivityManager.jsm:127
    getActivity resource://gre/modules/ActivityManager.jsm:127
    removeActivity resource://gre/modules/ActivityManager.jsm:80
    onFolderRemovedFromQ resource:///modules/activity/autosync.jsm:244
    _timerCallback resource:///modules/AppIdleManager.jsm:30
SyntaxError: redeclaration of const THUNDERBIRD_THEME_PREVIEWS
aboutAddonsExtra.js:1:1
Uncaught SyntaxError: redeclaration of const THUNDERBIRD_THEME_PREVIEWS
    <anonymous> chrome://messenger/content/aboutAddonsExtra.js:1
    observe chrome://messenger/content/specialTabs.js:1717
aboutAddonsExtra.js:1:1
NS_ERROR_NOT_AVAILABLE: ActivityManager.jsm:127
    getActivity resource://gre/modules/ActivityManager.jsm:127
    removeActivity resource://gre/modules/ActivityManager.jsm:80
    onFolderRemovedFromQ resource:///modules/activity/autosync.jsm:244
    _timerCallback resource:///modules/AppIdleManager.jsm:30

​
#156 is similar, but _not_ the same.  #129 appears related, but again is _not_ the same.  #138 is the closest to my problem, but it happens for all my events, not just recurring ones.

**Comment by FabianRahm** [comment] 2021-05-27 12:45
I can confirm this issue. 

From the Google Workspace admin logs, I see that the attendee was deleted through the Calendar API, named "Event guest removed".

**Comment by oyvindwe** [comment] 2021-05-31 16:42
I believe this is caused by this issue from back in 2009, which is still not fixed!

**Comment by viveksuraiya** [comment] 2021-06-23 06:48
In fact, if I create and event, invite attendees, and save and close the event in Thunderbird, the attendees are not saved! Please fix the problem!

**Comment by tomaytotomato** [comment] 2021-06-24 13:08
I can confirm this issue on Kubuntu Thunderbird.

Create event on Google Calendar.

When I get a reminder for the event on Thunderbird. If i hit the "Dismiss" button, it then removes everyone from it.

**Comment by sepatel** [comment] 2021-06-30 03:08
Ditto, having the same bug, even creating a brand new meeting and inviting someone immediately strips them off. All meetings setup directly via google end up getting removed when calender resync takes place. This is a complete show stopper.

**Comment by Salubritas** [comment] 2021-07-07 12:47
Seeing this too. Calendly creates meetings in my Google calendar. If I open the meeting in TBird then close and save, the invitees are deleted and the meeting gets removed from their calendar! Has been happening for a while but only realized it was happening from TBird today.

**Comment by viveksuraiya** [comment] 2021-07-08 00:56
I have moved to CalDAV to sync my Google calendars. If you have any sub-calendars, you may use the calendar IDs from the Google calendar settings in the browser to configure them.

**Comment by oyvindwe** [comment] 2021-07-08 07:52
Moving to CalDAV was my fix as well. iCal is another possibility, but I had some problems with that as well. I forgot to mention that in my previous comment (it is so long since i moved to CalDAV that I had forgotten about it). It's a bit tricky to find the id to subscribe to additional calendars.

**Comment by sepatel** [comment] 2021-07-08 16:58
> I have moved to CalDAV to sync my Google calendars. If you have any sub-calendars, you may use the calendar IDs from the Google calendar settings in the browser to configure them.

Thank you very much. I didn't even realize I could really do this. Been years since I remember doing it and completely slipped my mind. For anyone else, this is stupid simple to do. Just use the following URL as the CalDAV

`https://apidata.googleusercontent.com/caldav/v2/calid/events`

And replace the **_calid_** with your gmail email (or the calendar id if it is not the default calendar you desire)

**Comment by kewisch** [comment] 2021-09-04 23:06
Acknowledging this. With attendees disabled and the way the Provider currently modifies events, this will be a problem. This should be fixed on the `main` branch, but I'm leaving this open to see if I can fix it for 91/legacy as well.

**Comment by kewisch** [comment] 2021-09-15 21:00
So in a sense, this is fixed in 8a86dd5cbd833a70813872995f4b2ed64681759e and abc3a417dcf7b6940f599140523f216eca846af4. The legacy prefs are migrated correctly, and there is an options screen in the add-ons manager that allows changing them.

What I did not do (yet?) is enable syncing attendees unconditionally. I don't recall the context on actually needing to disable syncing attendees as opposed to just disabling sending notifications. From today's perspective it makes sense to just sync the attendees. 

I guess the only concerns I have is that if something doesn't go as planned, it will be very embarrassing for folks: imagine you edit some minor detail on your copy of an invitation, and instead you send your own invites to everyone on the meeting.

I believe I'm going to keep it this way and let folks enable themselves. Version 91.1.0 will be a complete rewrite, and I'm a bit less concerned there due to the way I'm modifying events and have enabled attendees unconditionally there.

**Closed by kewisch** 2021-09-15 21:00 UTC
Labels: defect
