### ISSUE TITLE
Accepting invitations via email does not work (config calendar.google.enableEmailInvitations is deleted from config file)

### ISSUE THREAD

**Issue by mhobl** [kewisch/gdata-provider#134] opened 2020-11-12 11:20 UTC
### Describe the problem and steps to reproduce it:

Accepting invitations via email was possible with the configuration:
calendar.google.enableEmailInvitations = true
If I add this configuration accepting inviations via email work.

### What happened?

If I restart TB, then the configuration calendar.google.enableEmailInvitations is removed from the configuration file.
Therefore accepting invitations via email does not work anymore.

### What did you expect to happen?

The configuration calendar.google.enableEmailInvitations should not be deleted from the configuration file.

Running on Windows 10
Thunderbird 78.4.3
Provider 78.0.1

**Comment by gmarget** [comment] 2020-11-17 08:52
I confirm that the same situation occurred for me as well, when my Thunderbird was updated automatically. After the update, I cannot add invitations included in emails, instead I get the following message "no writable calendars are configured for invitations please check the calendar properties".

**Comment by Coach78** [comment] 2020-11-20 15:20
I'm having the same problem: I can add meetings in the google calendar via TB. That works fine. But if I try to accept an Invitation from an email I get the error message: "no writable calendars are configured for invitations please check the calendar properties" 

I am using a diffrent Account for the Emails though. Therefor the Email Invitation are not send to my googlemail account, but to my work account, which I am using in TB. Could that be the problem?

Thanx for any help!

**Comment by mcanonic** [comment] 2020-11-25 16:40
I solved it by adding a local calendar.
No sense, but it works.
The only problem is that it sometimes I miss the event description, pretty annoing.

**Comment by GCAPITAINE303** [comment] 2020-11-26 07:36
Hello

same problem and very important to find a solution !! thank you

**Comment by GCAPITAINE303** [comment] 2020-11-26 08:56
only the local diaries work but not when they are in network

**Comment by twain28** [comment] 2020-11-26 10:17
Duplicate of issue #63

**Comment by aerobaticant** [comment] 2020-12-02 11:04
Same for me too.

**Comment by antworks-hub** [comment] 2020-12-03 09:30
Same here.

**Comment by MarcusAhlfors** [comment] 2020-12-04 13:51
same here

**Comment by antworks-hub** [comment] 2020-12-04 14:29
here I found a partially working solution , waiting for a definitive one: https://github.com/kewisch/gdata-provider/issues/63#issuecomment-735366481

I tested that extension and it worked for me.

**Comment by r-a-y** [comment] 2020-12-11 05:06
I found that setting `calendar.google.enableAttendees` to `true` in the Config Editor works.

Most likely you need to create this preference. To do this, go to "Options > General" and scroll down to the bottom of the page and click on the "Config Editor" button.

Next, right click and select "New", followed by "Boolean" and create the pref and set it to `true`.

You will also need to set `calendar.google.enableEmailInvitations` to true as well if you haven't already.

This is all outlined on the wiki page - https://github.com/kewisch/gdata-provider/wiki/FAQ#missing-features.

Hope that helps! I'm using latest versions of both Provider and TB.

**Comment by mhobl** [comment] 2020-12-11 09:12
The problem is that all settings "old" settings will be purged if  you restart TB.
I've already fixed this for me by removing the purge function from the source code, but this is not the best solution.
As already stated out by Kewisch (https://github.com/kewisch/gdata-provider/issues/63#issuecomment-719928858) the fix is here that the properties will be loaded from the storage.local.

If I have some more time, maybe I can publish such a solution.

**Comment by r-a-y** [comment] 2020-12-11 09:25
Yeah, it's a temporary solution. I've switched to using Lightning's native CalDAV support and using Google Calendar's CalDAV URL instead.

I do miss the Google Calendar Tasks integration with Provider though, but I can live without it for now.

**Comment by GCAPITAINE303** [comment] 2020-12-17 07:32
Hello

Do you have a solution that can be provided because I will have to switch to outlook but this solution does not please me thank you

**Comment by osch4** [comment] 2021-01-07 11:23
> Most likely you need to create this preference. To do this, go to "Options > General" and scroll down to the bottom of the page and click on the "Config Editor" button.
> 
> Next, right click and select "New", followed by "Boolean" and create the pref and set it to `true`.
> 
> You will also need to set `calendar.google.enableEmailInvitations` to true as well if you haven't already.
> 
> This is all outlined on the wiki page - https://github.com/kewisch/gdata-provider/wiki/FAQ#missing-features.
> 
> Hope that helps! I'm using latest versions of both Provider and TB.

This works for me. Thank you!

**Comment by nigelboor** [comment] 2021-07-19 11:55
I have this problem on MacOS but it seems to be associated with disabling the local calendar.
One re-enabled all the functionality returns.

**Comment by kewisch** [comment] 2021-09-06 22:10
I will be resolving this as part of #191

**Closed by kewisch** 2021-09-06 22:10 UTC
