### ISSUE TITLE
No writable calendars are configured for invitations

### ISSUE THREAD

**Issue by fdepub** [kewisch/gdata-provider#151] opened 2021-01-07 15:59 UTC
### Describe the problem and steps to reproduce it:

When I receive an invitation, I can't add it in my google calendar.

### What happened?

Nothing, I just have the message "No writable calendars are configured for invitations, please check calendar properties" in top of the email invitation. 

### What did you expect to happen?

I would like to add invitation in my google calendar

**Comment by johannesE** [comment] 2021-01-08 11:57
I have the same issue since I upgraded to Ubuntu 20.10 (which I think also updated thunderbird to 78.5.0). Everything was working fine before that.

**Comment by crossow** [comment] 2021-01-08 13:22
Same here, on a Windows 10 system. I can create an _about:config_ entry `calendar.google.enableEmailInvitations = true` to solve this problem temporarily. However, whenever I restart Thunderbird, this config value disappears, and recreating it manually is cumbersome.

**Comment by Confusion** [comment] 2021-01-09 14:19
This is probably a duplicate of #63. The workaround by @crossow seems to be the best option for now. See https://github.com/kewisch/gdata-provider/issues/63#issuecomment-757062879 if you also want a workaround for #103 (and its duplicates #121, #129, #138, #147)

**Comment by johannesE** [comment] 2021-01-09 17:17
Thanks!
Right click to create new config entries.

**Comment by dmarteau** [comment] 2021-01-15 17:28
This does not work because of https://github.com/kewisch/gdata-provider/issues/63#issuecomment-759424469:  

The code responsible for that behavior appears to be here: https://github.com/kewisch/gdata-provider/blob/master/src/api/gdata.js#L99

**Comment by thwaller** [comment] 2021-02-08 00:36
I have this same issue and have read the other threads referenced. While there are a lot of solutions and different outcomes, I wanted to share what works for me. In the Preferences -> General -> Config Editor, I add the following:
1. calendar.google.enableAttendees;true
2. calendar.google.enableEmailInvitations;true
3. calendar.google.sendEventNotifications;true

I experience no problems with adding these three settings aside from they disappear after TB is restarted. The settings need to be added as new (type boolean), there is no existing setting for any of the three, as is explained in the other threads.

I know there is a patched xpi file mentioned in the other threads, I have not tried it yet.

**Comment by WLR86** [comment] 2021-02-11 09:06
I'm experiencing the very same issue at work (dozens of computers) - it's totally untenable to expect end users manually adding three configuration boolean options each time they restart TB - @twaller : I'm going to try to find that patched xpi you mentionned, thanks for your feedback

**Comment by kewisch** [comment] 2021-09-06 22:15
Fixing this as part of #191

**Closed by kewisch** 2021-09-06 22:15 UTC
