### ISSUE TITLE
Cannot add attendees to event 

### ISSUE THREAD

**Issue by roccopietrini** [kewisch/gdata-provider#129] opened 2020-11-06 15:26 UTC
### Describe the problem and steps to reproduce it:

I cannot invite attendees to any event. 
- Create an event, add attendees

### What happened?
"invite attendees" is disabled (greyed out). After closing the event window attendees disappear. 

### What did you expect to happen?

Attendees are saved and notified.
[console-export-2020-11-6_16-14-35.txt](https://github.com/kewisch/gdata-provider/files/5501995/console-export-2020-11-6_16-14-35.txt)

### Anything else we should know?

Thunderbird version 78.4.1

**Comment by ostroskyjeremiah** [comment] 2020-11-07 16:07
Confirming I have same issue.  If I create the event via the google calendar in a web browser, the attendees are saved, but creating via Thunderbird 78.4.1 and google provider 78.0.1.  

![TBGCal-error1](https://user-images.githubusercontent.com/10487919/98446108-693ce780-20e9-11eb-8580-7162eef7810c.jpg)

![TBGCal-error2](https://user-images.githubusercontent.com/10487919/98446111-69d57e00-20e9-11eb-94da-1b19ceed81d6.jpg)

**Comment by GerdaKuschel** [comment] 2020-11-12 03:59
Hi - I have been having exactly the same problems since Thunderbird went to the new 78 version despite using the new Google Provider

Can someone please advise when this will be fixed?

**Comment by tdp-aus** [comment] 2020-11-17 00:02
I'm having the same problem. Attendees do not get invitations and when I close the event. the attendees names disappear. I didn't realise this was happening, but can date the problem back to when I updated to latest version 78.

**Comment by tpierschel** [comment] 2020-11-17 11:47
Same here: 78.0.1 with TB 78.4.3

**Comment by fedeelgarcia** [comment] 2020-12-11 10:27
Same here: 78.0.1 with TB 78.5.1 (32 bits) with W7

**Comment by cjwhelan3** [comment] 2021-02-24 06:13
Same problem TB 78.7.1 (32-bit) / Provider for Google Calendar 78.0.1

**Comment by Bbillyben** [comment] 2021-03-09 16:44
Exact Same issue TB 78.7.1 (64 bits) / Provider for google calendar 78.0.1

Error in console :
```
Lightning: [calGoogleCalendar] Failed freebusy request: [Exception... "A request Error Occurred. Status Code: 400 Bad Request Body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gdata-provider/legacy/modules/gdataRequest.jsm :: fail :: line 232"  data: no]

``

**Comment by kewisch** [comment] 2021-09-04 23:41
I've identified the cause for this, there is another ticket open to cover the work

**Closed by kewisch** 2021-09-04 23:41 UTC
